CREATE DATABASE qoe_help;
USE qoe_help;

CREATE TABLE NODES (
ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
PLANO VARCHAR(30) NOT NULL,
CMTS VARCHAR(30) DEFAULT "-",
REGION VARCHAR(10) DEFAULT "-"
);

CREATE TABLE STATUS_NODE (
ID_NODE INT NOT NULL,
DEPENDENCIA VARCHAR(20) DEFAULT "-",
IMPEDIMENTO VARCHAR(20) DEFAULT "-",
REVISION DATE,
TIPO VARCHAR(8) DEFAULT "-",
PROBLEMA VARCHAR(25) DEFAULT "-",
ESTADO VARCHAR(25) DEFAULT "-",
DETALLE VARCHAR(400) DEFAULT "-",
CONSTRAINT FK_ID_NODE_STATUS FOREIGN KEY (ID_NODE) REFERENCES NODES (ID)
);

CREATE TABLE NEW_QOE (
ID_NODE INT NOT NULL,
CONSTRAINT FK_ID_NODE_QOE FOREIGN KEY (ID_NODE) REFERENCES NODES (ID)
);

CREATE TABLE NEW_HOURS (
ID_NODE INT NOT NULL,
CONSTRAINT FK_ID_NODE_HOURS FOREIGN KEY (ID_NODE) REFERENCES NODES (ID)
);

CREATE TABLE AFECTED_DAYS (
ID_NODE INT NOT NULL,
CONSTRAINT FK_ID_NODE_AFECTED FOREIGN KEY (ID_NODE) REFERENCES NODES (ID)
);

CREATE TABLE PERIOD (
ID_NODE INT NOT NULL,
CONSTRAINT FK_ID_NODE_PERIOD FOREIGN KEY (ID_NODE) REFERENCES NODES (ID)
);

CREATE TABLE MODULATION (
ID_NODE INT NOT NULL,
CONSTRAINT FK_ID_NODE_MOD FOREIGN KEY (ID_NODE) REFERENCES NODES (ID)
);

CREATE TABLE SAMPLING (
ID_NODE INT NOT NULL,
CONSTRAINT FK_ID_NODE_SAMPLING FOREIGN KEY (ID_NODE) REFERENCES NODES (ID)
);

CREATE TABLE IMPACTEDMODEMS (
ID_NODE INT NOT NULL,
CONSTRAINT FK_ID_NODE_IMPACTEDMODEMS FOREIGN KEY (ID_NODE) REFERENCES NODES (ID)
);

CREATE TABLE STRESSEDMODEMS (
ID_NODE INT NOT NULL,
CONSTRAINT FK_ID_NODE_STRESSEDMODEMS FOREIGN KEY (ID_NODE) REFERENCES NODES (ID)
);

SELECT (SELECT ID FROM NODES WHERE PLANO = 'LMJL155'), ID_NODE FROM NEW_QOE;
SELECT ID FROM NODES WHERE PLANO = 'LMJL155';

ALTER TABLE NEW_QOE
ADD COLUMN `20/11/2021` FLOAT AFTER ID_NODE;

INSERT INTO NEW_QOE (ID_NODE, `20/11/2021`)
VALUES ((SELECT ID FROM NODES WHERE PLANO = 'LMJL155'), 98 );

SELECT `20/11/2021` FROM NEW_QOE
WHERE ID_NODE = (SELECT ID FROM NODES WHERE PLANO = 'LMJL155');
#######################################################################
DROP TABLE NEW_QOE;
DROP TABLE NEW_HOURS;
DROP TABLE STATUS_NODE;
DROP TABLE PERIOD;
DROP TABLE AFECTED_DAYS;
DROP TABLE MODULATION;
DROP TABLE SAMPLING;
DROP TABLE IMPACTEDMODEMS;
DROP TABLE STRESSEDMODEMS;
DROP TABLE NODES;

USE QOE_HELP;
ALTER TABLE NEW_QOE
DROP COLUMN `03/01/2022`;
ALTER TABLE NEW_HOURS
DROP COLUMN `03/01/2022`;
ALTER TABLE PERIOD
DROP COLUMN `03/01/2022`;
ALTER TABLE AFECTED_DAYS
DROP COLUMN `03/01/2022`;
ALTER TABLE MODULATION
DROP COLUMN `03/01/2022`;
ALTER TABLE SAMPLING
DROP COLUMN `03/01/2022`;
ALTER TABLE IMPACTEDMODEMS
DROP COLUMN `03/01/2022`;
ALTER TABLE STRESSEDMODEMS
DROP COLUMN `03/01/2022`;

SELECT * FROM NEW_QOE;
SELECT * FROM NEW_HOURS;
SELECT * FROM PERIOD;
SELECT * FROM AFECTED_DAYS;
SELECT * FROM STATUS_NODE;
SELECT * FROM NODES
WHERE PLANO = 'LMCH006';
SELECT * FROM MODULATION;
SELECT * FROM SAMPLING;
SELECT * FROM IMPACTEDMODEMS;
SELECT * FROM STRESSEDMODEMS;

# TABLA DE DIARIO
SELECT PLANO,
NEW_QOE.`02/01/2022` AS QOE,
NEW_HOURS.`02/01/2022` AS HOURS,
PERIOD.`02/01/2022` AS PERIOD,
MODULATION.`02/01/2022` AS MODULATION,
SUM(AFECTED_DAYS.`02/01/2022` + AFECTED_DAYS.`01/01/2022`) AS DAYS
FROM NODES
INNER JOIN NEW_QOE ON NEW_QOE.ID_NODE = NODES.ID
INNER JOIN NEW_HOURS ON NEW_HOURS.ID_NODE = NODES.ID
INNER JOIN PERIOD ON PERIOD.ID_NODE = NODES.ID
INNER JOIN MODULATION ON MODULATION.ID_NODE = NODES.ID
INNER JOIN AFECTED_DAYS ON NODES.ID = AFECTED_DAYS.ID_NODE
WHERE AFECTED_DAYS.ID_NODE IN (
SELECT ID_NODE FROM AFECTED_DAYS
WHERE `02/01/2022` + `01/01/2022` >= 2)
OR AFECTED_DAYS.ID_NODE IN (
SELECT ID_NODE FROM MODULATION
WHERE `02/01/2022` >= 1 AND `01/01/2022` >= 1)
GROUP BY AFECTED_DAYS.ID_NODE
ORDER BY DAYS DESC;

# TABLA DE MODUALCIÓN
SELECT PLANO, `06/12/2021`, `05/12/2021`, `04/12/2021` FROM MODULATION
INNER JOIN NODES ON NODES.ID = MODULATION.ID_NODE
WHERE ID_NODE IN (
SELECT ID_NODE FROM MODULATION
WHERE `06/12/2021` >= 1 AND `05/12/2021` >= 1);

# PRIORIDAD GENERAL
SELECT PLANO, DEPENDENCIA, IMPEDIMENTO, DATE_FORMAT(REVISION, '%Y-%m-%d') AS REVISION, TIPO, SUM(`02/01/2022` + `01/01/2022`) AS DAYS, PROBLEMA, ESTADO FROM STATUS_NODE
INNER JOIN NODES ON NODES.ID = STATUS_NODE.ID_NODE
INNER JOIN AFECTED_DAYS ON NODES.ID = AFECTED_DAYS.ID_NODE
WHERE STATUS_NODE.ID_NODE IN (
SELECT ID_NODE FROM AFECTED_DAYS
WHERE `02/01/2022` + `01/01/2022` >= 2)
GROUP BY STATUS_NODE.ID_NODE
ORDER BY DAYS DESC;

# PRIORIDAD QOE
SELECT PLANO, TIPO, SUM(AFECTED_DAYS.`06/12/2021` + AFECTED_DAYS.`05/12/2021`) AS DAYS, PROBLEMA, ESTADO, NEW_QOE.`06/12/2021`, NEW_QOE.`05/12/2021` FROM NEW_QOE
INNER JOIN NODES ON NODES.ID = NEW_QOE.ID_NODE
INNER JOIN STATUS_NODE ON NODES.ID = STATUS_NODE.ID_NODE
INNER JOIN AFECTED_DAYS ON NODES.ID = AFECTED_DAYS.ID_NODE
WHERE NEW_QOE.ID_NODE IN (
SELECT ID_NODE FROM AFECTED_DAYS
WHERE `06/12/2021` + `05/12/2021` >= 1)
GROUP BY STATUS_NODE.ID_NODE
ORDER BY DAYS DESC;

# PRIORIDAD HOURS
SELECT PLANO, TIPO, SUM(AFECTED_DAYS.`06/12/2021` + AFECTED_DAYS.`05/12/2021` + AFECTED_DAYS.`04/12/2021`) AS DAYS, PROBLEMA, ESTADO, NEW_HOURS.`06/12/2021`, NEW_HOURS.`05/12/2021`, NEW_HOURS.`04/12/2021` FROM NEW_HOURS
INNER JOIN NODES ON NODES.ID = NEW_HOURS.ID_NODE
INNER JOIN STATUS_NODE ON NODES.ID = STATUS_NODE.ID_NODE
INNER JOIN AFECTED_DAYS ON NODES.ID = AFECTED_DAYS.ID_NODE
WHERE NEW_HOURS.ID_NODE IN (
SELECT ID_NODE FROM AFECTED_DAYS
WHERE `06/12/2021` + `05/12/2021` +`04/12/2021` >= 2)
GROUP BY STATUS_NODE.ID_NODE
ORDER BY DAYS DESC;

# PRIORIDAD PERIOD
SELECT PLANO, TIPO, SUM(AFECTED_DAYS.`06/12/2021` + AFECTED_DAYS.`05/12/2021`) AS DAYS, PROBLEMA, ESTADO, PERIOD.`06/12/2021`, PERIOD.`05/12/2021` FROM PERIOD
INNER JOIN NODES ON NODES.ID = PERIOD.ID_NODE
INNER JOIN STATUS_NODE ON NODES.ID = STATUS_NODE.ID_NODE
INNER JOIN AFECTED_DAYS ON NODES.ID = AFECTED_DAYS.ID_NODE
WHERE PERIOD.ID_NODE IN (
SELECT ID_NODE FROM AFECTED_DAYS
WHERE `06/12/2021` + `05/12/2021` >= 1)
GROUP BY STATUS_NODE.ID_NODE
ORDER BY DAYS DESC;

# PRIORIDAD MODULATION
SELECT PLANO, TIPO, SUM(AFECTED_DAYS.`06/12/2021` + AFECTED_DAYS.`05/12/2021` + AFECTED_DAYS.`04/12/2021`) AS DAYS, PROBLEMA, ESTADO, MODULATION.`06/12/2021`, MODULATION.`05/12/2021`, MODULATION.`04/12/2021` FROM MODULATION
INNER JOIN NODES ON NODES.ID = MODULATION.ID_NODE
INNER JOIN STATUS_NODE ON NODES.ID = STATUS_NODE.ID_NODE
INNER JOIN AFECTED_DAYS ON NODES.ID = AFECTED_DAYS.ID_NODE
WHERE MODULATION.ID_NODE IN (
SELECT ID_NODE FROM AFECTED_DAYS
WHERE `06/12/2021` + `05/12/2021` +`04/12/2021` >= 2)
GROUP BY STATUS_NODE.ID_NODE
ORDER BY DAYS DESC;

SELECT CMTS, PLANO, `10/12/2021`, `09/12/2021` FROM NODES
INNER JOIN NEW_QOE ON NEW_QOE.ID_NODE = NODES.ID
WHERE PLANO REGEXP '^';

UPDATE STATUS_NODE
SET DEPENDENCIA = 'NINGUNO', IMPEDIMENTO = 'NINGUNO', REVISION = '2021-12-19', TIPO = 'US', PROBLEMA = 'NINGUNO', ESTADO = 'NINGUNO', DETALLE = 'Tx sec'
WHERE ID_NODE = (SELECT ID FROM NODES WHERE PLANO = 'LMCH006');

SELECT * FROM STATUS_NODE;

SELECT CMTS, PLANO, DEPENDENCIA, IMPEDIMENTO, DATE_FORMAT(REVISION, '%Y-%m-%d') AS REVISION, TIPO, SUM(`02/01/2022` + `01/01/2022`) AS DAYS, PROBLEMA, ESTADO, DETALLE FROM STATUS_NODE
    INNER JOIN NODES ON NODES.ID = STATUS_NODE.ID_NODE
    INNER JOIN AFECTED_DAYS ON NODES.ID = AFECTED_DAYS.ID_NODE
    WHERE STATUS_NODE.ID_NODE = (SELECT ID FROM NODES WHERE PLANO = 'LMLO010')
    GROUP BY STATUS_NODE.ID_NODE
    ORDER BY DAYS DESC, ID DESC;

SELECT CMTS, PLANO, `02/01/2022`, `01/01/2022` FROM SAMPLING
INNER JOIN NODES ON NODES.ID = SAMPLING.ID_NODE
WHERE `02/01/2022` < 90 OR  `01/01/2022` < 90;

SELECT COUNT(`02/01/2022`) FROM NEW_QOE
WHERE `02/01/2022`<= 70 AND `02/01/2022` > 0;
SELECT COUNT(`02/01/2022`) FROM NEW_QOE
WHERE `02/01/2022`> 70 AND `02/01/2022` <= 80;
SELECT COUNT(`02/01/2022`) FROM NEW_HOURS
WHERE `02/01/2022`>= 3;


ALTER TABLE NODES ADD COLUMN REGION VARCHAR(10) DEFAULT '-' AFTER CMTS;

SET SQL_SAFE_UPDATES = 0;
UPDATE NODES
SET REGION = '-'
WHERE PLANO = 'LMSQ039';

SELECT * FROM NODES;

SELECT REGION, CMTS, PLANO, `01/01/2022`  FROM NODES
INNER JOIN NEW_QOE ON NEW_QOE.ID_NODE = NODES.ID
WHERE PLANO REGEXP '^LMLO' AND REGION = 'LIMA';

SELECT REGION, CMTS, PLANO, DEPENDENCIA, IMPEDIMENTO, DATE_FORMAT(REVISION, '%Y-%m-%d') AS REVISION, TIPO, SUM(`01/01/2022`) AS DAYS, PROBLEMA, ESTADO, DETALLE FROM STATUS_NODE
        INNER JOIN NODES ON NODES.ID = STATUS_NODE.ID_NODE
        INNER JOIN AFECTED_DAYS ON NODES.ID = AFECTED_DAYS.ID_NODE
        WHERE STATUS_NODE.ID_NODE IN (
        SELECT ID_NODE FROM AFECTED_DAYS
        WHERE `01/01/2022` >= 2) AND REGION = 'LIMA' 
        GROUP BY STATUS_NODE.ID_NODE
        ORDER BY DAYS DESC, ID DESC;

#SELECT IF ( EXISTS(
#SELECT * FROM information_schema.COLUMNS 
#WHERE TABLE_SCHEMA = 'qoehelp' AND TABLE_NAME = 'hours' 
#AND COLUMN_NAME = '09/11/2021'
#),1,0);

#SELECT HOST, USER, PLUGIN FROM MYSQL.USER;

#drop database qoehelp;