CREATE DATABASE qoehelp;
USE qoehelp;

CREATE TABLE NODES (
ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
PLANO VARCHAR(10) NOT NULL
);

CREATE TABLE STATUS_NODE (
ID_NODE INT NOT NULL,
DEPENDENCIA ENUM('CALIDAD', 'OYM', 'CICSA', 'COTENER', 'IMPEDIMENTO'),
IMPEDIMENTO ENUM('C. COMERCIAL','MERCADO','MÓDULOS','EDIFICIO','PROVINCIA','SEDE CLARO','ZONA RIESGOZA','NINGUNO'),
REVISION DATE,
TIPO ENUM('US','DS','T3'),
PROBLEMA ENUM('RUIDO','MÓDULO RF AVERIADO','RUIDO NOCHE','RUIDO INTERMITENTE','CMs AFECTADOS','AVERIA','PERFORMANCE'),
ESTADO ENUM('POR AGENDAR','ATENDIDO - SOLUCIONADO','ATENDIDO - NO TERMINADO'),
DETALLE VARCHAR(300),
CONSTRAINT FK_ID_NODE_STATUS FOREIGN KEY (ID_NODE) REFERENCES NODES (ID)
);

CREATE TABLE NEW_HOURS (
ID_NODE INT NOT NULL,
CONSTRAINT FK_ID_NODE_HOURS FOREIGN KEY (ID_NODE) REFERENCES NODES (ID)
);

CREATE TABLE NEW_QOE (
ID_NODE INT NOT NULL,
CONSTRAINT FK_ID_NODE_QOE FOREIGN KEY (ID_NODE) REFERENCES NODES (ID)
);

CREATE TABLE AFECTED_DAYS (
ID_NODE INT NOT NULL,
CONSTRAINT FK_ID_NODE_AFECTED FOREIGN KEY (ID_NODE) REFERENCES NODES (ID)
);

CREATE TABLE PERIOD (
ID_NODE INT NOT NULL,
CONSTRAINT FK_ID_NODE_PERIOD FOREIGN KEY (ID_NODE) REFERENCES NODES (ID)
);

CREATE TABLE MODULATION (
ID_NODE INT NOT NULL,
CONSTRAINT FK_ID_NODE_MOD FOREIGN KEY (ID_NODE) REFERENCES NODES (ID)
);

SELECT (SELECT ID FROM NODES WHERE PLANO = 'LMJL155'), ID_NODE FROM NEW_QOE;
SELECT ID FROM NODES WHERE PLANO = 'LMJL155';

ALTER TABLE NEW_QOE
ADD COLUMN `20/11/2021` FLOAT AFTER ID_NODE;

INSERT INTO NEW_QOE (ID_NODE, `20/11/2021`)
VALUES ((SELECT ID FROM NODES WHERE PLANO = 'LMJL155'), 98 );

SELECT `20/11/2021` FROM NEW_QOE
WHERE ID_NODE = (SELECT ID FROM NODES WHERE PLANO = 'LMJL155');
#######################################################################
DROP TABLE NEW_QOE;
DROP TABLE NEW_HOURS;
DROP TABLE STATUS_NODE;
DROP TABLE PERIOD;
DROP TABLE AFECTED_DAYS;
DROP TABLE MODULATION;

ALTER TABLE NEW_QOE
DROP COLUMN `06/12/2021`;
ALTER TABLE NEW_HOURS
DROP COLUMN `06/12/2021`;
ALTER TABLE PERIOD
DROP COLUMN `06/12/2021`;
ALTER TABLE AFECTED_DAYS
DROP COLUMN `06/12/2021`;
ALTER TABLE MODULATION
DROP COLUMN `06/12/2021`;

SELECT * FROM NEW_QOE;
SELECT * FROM NEW_HOURS;
SELECT * FROM PERIOD;
SELECT * FROM AFECTED_DAYS;
SELECT * FROM STATUS_NODE;
SELECT * FROM NODES WHERE PLANO = 'LMCO116';
SELECT * FROM MODULATION;

# TABLA DE MODUALCIÓN
SELECT PLANO, `06/12/2021`, `05/12/2021`, `04/12/2021` FROM MODULATION INNER JOIN NODES ON NODES.ID = MODULATION.ID_NODE
WHERE ID_NODE IN (
SELECT ID_NODE FROM MODULATION
WHERE `06/12/2021` >= 1 AND `05/12/2021` >= 1);

# PRIORIDAD GENERAL
SELECT PLANO, DEPENDENCIA, IMPEDIMENTO, REVISION, TIPO, SUM(`06/12/2021` + `05/12/2021` + `04/12/2021`) AS DAYS, PROBLEMA, ESTADO FROM STATUS_NODE
INNER JOIN NODES ON NODES.ID = STATUS_NODE.ID_NODE
INNER JOIN AFECTED_DAYS ON NODES.ID = AFECTED_DAYS.ID_NODE
WHERE STATUS_NODE.ID_NODE IN (
SELECT ID_NODE FROM AFECTED_DAYS
WHERE `06/12/2021` + `05/12/2021` +`04/12/2021` >= 2)
GROUP BY STATUS_NODE.ID_NODE
ORDER BY DAYS DESC;

# PRIORIDAD QOE
SELECT PLANO, TIPO, SUM(AFECTED_DAYS.`06/12/2021` + AFECTED_DAYS.`05/12/2021` + AFECTED_DAYS.`04/12/2021`) AS DAYS, PROBLEMA, ESTADO, NEW_QOE.`06/12/2021`, NEW_QOE.`05/12/2021`, NEW_QOE.`04/12/2021` FROM NEW_QOE
INNER JOIN NODES ON NODES.ID = NEW_QOE.ID_NODE
INNER JOIN STATUS_NODE ON NODES.ID = STATUS_NODE.ID_NODE
INNER JOIN AFECTED_DAYS ON NODES.ID = AFECTED_DAYS.ID_NODE
WHERE NEW_QOE.ID_NODE IN (
SELECT ID_NODE FROM AFECTED_DAYS
WHERE `06/12/2021` + `05/12/2021` +`04/12/2021` >= 2)
GROUP BY STATUS_NODE.ID_NODE
ORDER BY DAYS DESC;

# PRIORIDAD HOURS
SELECT PLANO, TIPO, SUM(AFECTED_DAYS.`06/12/2021` + AFECTED_DAYS.`05/12/2021` + AFECTED_DAYS.`04/12/2021`) AS DAYS, PROBLEMA, ESTADO, NEW_HOURS.`06/12/2021`, NEW_HOURS.`05/12/2021`, NEW_HOURS.`04/12/2021` FROM NEW_HOURS
INNER JOIN NODES ON NODES.ID = NEW_HOURS.ID_NODE
INNER JOIN STATUS_NODE ON NODES.ID = STATUS_NODE.ID_NODE
INNER JOIN AFECTED_DAYS ON NODES.ID = AFECTED_DAYS.ID_NODE
WHERE NEW_HOURS.ID_NODE IN (
SELECT ID_NODE FROM AFECTED_DAYS
WHERE `06/12/2021` + `05/12/2021` +`04/12/2021` >= 2)
GROUP BY STATUS_NODE.ID_NODE
ORDER BY DAYS DESC;

# PRIORIDAD PERIOD
SELECT PLANO, TIPO, SUM(AFECTED_DAYS.`06/12/2021` + AFECTED_DAYS.`05/12/2021` + AFECTED_DAYS.`04/12/2021`) AS DAYS, PROBLEMA, ESTADO, PERIOD.`06/12/2021`, PERIOD.`05/12/2021`, PERIOD.`04/12/2021` FROM PERIOD
INNER JOIN NODES ON NODES.ID = PERIOD.ID_NODE
INNER JOIN STATUS_NODE ON NODES.ID = STATUS_NODE.ID_NODE
INNER JOIN AFECTED_DAYS ON NODES.ID = AFECTED_DAYS.ID_NODE
WHERE PERIOD.ID_NODE IN (
SELECT ID_NODE FROM AFECTED_DAYS
WHERE `06/12/2021` + `05/12/2021` +`04/12/2021` >= 2)
GROUP BY STATUS_NODE.ID_NODE
ORDER BY DAYS DESC;

# PRIORIDAD MODULATION
SELECT PLANO, TIPO, SUM(AFECTED_DAYS.`06/12/2021` + AFECTED_DAYS.`05/12/2021` + AFECTED_DAYS.`04/12/2021`) AS DAYS, PROBLEMA, ESTADO, MODULATION.`06/12/2021`, MODULATION.`05/12/2021`, MODULATION.`04/12/2021` FROM MODULATION
INNER JOIN NODES ON NODES.ID = MODULATION.ID_NODE
INNER JOIN STATUS_NODE ON NODES.ID = STATUS_NODE.ID_NODE
INNER JOIN AFECTED_DAYS ON NODES.ID = AFECTED_DAYS.ID_NODE
WHERE MODULATION.ID_NODE IN (
SELECT ID_NODE FROM AFECTED_DAYS
WHERE `06/12/2021` + `05/12/2021` +`04/12/2021` >= 2)
GROUP BY STATUS_NODE.ID_NODE
ORDER BY DAYS DESC;

#SELECT IF ( EXISTS(
#SELECT * FROM information_schema.COLUMNS 
#WHERE TABLE_SCHEMA = 'qoehelp' AND TABLE_NAME = 'hours' 
#AND COLUMN_NAME = '09/11/2021'
#),1,0);

#SELECT HOST, USER, PLUGIN FROM MYSQL.USER;

#drop database qoehelp;